In [1]:
import pandas as pd
import numpy as np
from flatten_json import flatten

In [12]:
def show_full_data(data, row_size=None, column_size=None, col_width=-1):
    """Shows all rows and columns instead of showing only some part and hiding other parts for large data.
    """
    with pd.option_context('display.max_rows', row_size, 'display.max_columns', column_size, 'display.max_colwidth', col_width):
        display(data)

# Class

In [2]:
with open('../../../student-life-dataset/dataset/education/class_info.json') as f:
    classes = json.load(f)

In [13]:
show_full_data(pd.DataFrame(flatten(classes), index=[0]))

,ANTH 012_location,ANTH 012_periods_0_day,ANTH 012_periods_0_end,ANTH 012_periods_0_start,ANTH 012_periods_1_day,ANTH 012_periods_1_end,ANTH 012_periods_1_start,ANTH 012_periods_2_day,ANTH 012_periods_2_end,ANTH 012_periods_2_start,ANTH 012_periods_3_day,ANTH 012_periods_3_end,ANTH 012_periods_3_start,BIOL 004_location,BIOL 004_periods_0_day,BIOL 004_periods_0_end,BIOL 004_periods_0_start,BIOL 004_periods_1_day,BIOL 004_periods_1_end,BIOL 004_periods_1_start,BIOL 004_periods_2_day,BIOL 004_periods_2_end,BIOL 004_periods_2_start,BIOL 006_location,BIOL 006_periods_0_day,BIOL 006_periods_0_end,BIOL 006_periods_0_start,BIOL 006_periods_1_day,BIOL 006_periods_1_end,BIOL 006_periods_1_start,BIOL 006_periods_2_day,BIOL 006_periods_2_end,BIOL 006_periods_2_start,CHIN 033_location,CHIN 033_periods_0_day,CHIN 033_periods_0_end,CHIN 033_periods_0_start,CHIN 033_periods_1_day,CHIN 033_periods_1_end,CHIN 033_periods_1_start,CHIN 033_periods_2_day,CHIN 033_periods_2_end,CHIN 033_periods_2_start,CHIN 033_periods_3_day,CHIN 033_periods_3_end,CHIN 033_periods_3_start,CHIN 033_periods_4_day,CHIN 033_periods_4_end,CHIN 033_periods_4_start,CHIN 062_location,CHIN 062_periods_0_day,CHIN 062_periods_0_end,CHIN 062_periods_0_start,CHIN 062_periods_1_day,CHIN 062_periods_1_end,CHIN 062_periods_1_start,CHIN 062_periods_2_day,CHIN 062_periods_2_end,CHIN 062_periods_2_start,COSC 007_location,COSC 007_periods_0_day,COSC 007_periods_0_end,COSC 007_periods_0_start,COSC 007_periods_1_day,COSC 007_periods_1_end,COSC 007_periods_1_start,COSC 007_periods_2_day,COSC 007_periods_2_end,COSC 007_periods_2_start,COSC 007_periods_3_day,COSC 007_periods_3_end,COSC 007_periods_3_start,COSC 020_location,COSC 020_periods_0_day,COSC 020_periods_0_end,COSC 020_periods_0_start,COSC 020_periods_1_day,COSC 020_periods_1_end,COSC 020_periods_1_start,COSC 020_periods_2_day,COSC 020_periods_2_end,COSC 020_periods_2_start,COSC 027_location,COSC 027_periods_0_day,COSC 027_periods_0_end,COSC 027_periods_0_start,COSC 027_periods_1_day,COSC 027_periods_1_end,COSC 027_periods_1_start,COSC 027_periods_2_day,COSC 027_periods_2_end,COSC 027_periods_2_start,COSC 050_location,COSC 050_periods_0_day,COSC 050_periods_0_end,COSC 050_periods_0_start,COSC 050_periods_1_day,COSC 050_periods_1_end,COSC 050_periods_1_start,COSC 050_periods_2_day,COSC 050_periods_2_end,COSC 050_periods_2_start,COSC 050_periods_3_day,COSC 050_periods_3_end,COSC 050_periods_3_start,COSC 057_location,COSC 057_periods_0_day,COSC 057_periods_0_end,COSC 057_periods_0_start,COSC 057_periods_1_day,COSC 057_periods_1_end,COSC 057_periods_1_start,COSC 057_periods_2_day,COSC 057_periods_2_end,COSC 057_periods_2_start,COSC 057_periods_3_day,COSC 057_periods_3_end,COSC 057_periods_3_start,COSC 060_location,COSC 060_periods_0_day,COSC 060_periods_0_end,COSC 060_periods_0_start,COSC 060_periods_1_day,COSC 060_periods_1_end,COSC 060_periods_1_start,COSC 060_periods_2_day,COSC 060_periods_2_end,COSC 060_periods_2_start,COSC 060_periods_3_day,COSC 060_periods_3_end,COSC 060_periods_3_start,COSC 065_location,COSC 065_periods_0_day,COSC 065_periods_0_end,COSC 065_periods_0_start,COSC 065_periods_1_day,COSC 065_periods_1_end,COSC 065_periods_1_start,COSC 065_periods_2_day,COSC 065_periods_2_end,COSC 065_periods_2_start,COSC 065_periods_3_day,COSC 065_periods_3_end,COSC 065_periods_3_start,COSC 069_location,COSC 069_periods_0_day,COSC 069_periods_0_end,COSC 069_periods_0_start,COSC 069_periods_1_day,COSC 069_periods_1_end,COSC 069_periods_1_start,COSC 069_periods_2_day,COSC 069_periods_2_end,COSC 069_periods_2_start,COSC 070_location,COSC 070_periods_0_day,COSC 070_periods_0_end,COSC 070_periods_0_start,COSC 070_periods_1_day,COSC 070_periods_1_end,COSC 070_periods_1_start,COSC 070_periods_2_day,COSC 070_periods_2_end,COSC 070_periods_2_start,COSC 077_location,COSC 077_periods_0_day,COSC 077_periods_0_end,COSC 077_periods_0_start,COSC 077_periods_1_day,COSC 077_periods_1_end,COSC 077_periods_1_start,COSC 077_periods_2_day,COSC 077_periods_2_end,COSC 077_periods_2_start,COSC 089 1_location,COSC 089 1_periods_0_day,COSC 089 1_periods_0_end,COSC 089 1_periods_0_start,COSC 089 1_periods_1_day,COSC 089 1_periods_1_end,COSC 089 1_periods_1_start,COSC 089 1_periods_2_day,COSC 089 1_periods_2_end,COSC 089 1_periods_2_start,COSC 089 1_periods_3_day,COSC 089 1_periods_3_end,COSC 089 1_periods_3_start,COSC 089 2_location,COSC 089 2_periods_0_day,COSC 089 2_periods_0_end,COSC 089 2_periods_0_start,COSC 089 2_periods_1_day,COSC 089 2_periods_1_end,COSC 089 2_periods_1_start,COSC 089 2_periods_2_day,COSC 089 2_periods_2_end,COSC 089 2_periods_2_start,COSC 089 3_location,COSC 089 3_periods_0_day,COSC 089 3_periods_0_end,COSC 089 3_periods_0_start,COSC 089 3_periods_1_day,COSC 089 3_periods_1_end,COSC 089 3_periods_1_start,COSC 089 3_periods_2_day,COSC 089 3_periods_2_end,COSC 089 3_periods_2_start,EARS 003_location,EARS 003_periods_0_day,EARS 003_periods_0_end,EARS 003_periods_0_start,EARS 003_periods_1_day,EARS 003_periods_1_end,EARS 003_periods_1_start,EARS 003_periods_2_day,EARS 003_periods_2_end,EARS 003_periods_2_start,EARS 003_periods_3_day,EARS 003_periods_3_end,EARS 003_periods_3_start,ECON 024_location,ECON 024_periods_0_day,ECON 024_periods_0_end,ECON 024_periods_0_start,ECON 024_periods_1_day,ECON 024_periods_1_end,ECON 024_periods_1_start,ECON 024_periods_2_day,ECON 024_periods_2_end,ECON 024_periods_2_start,ECON 024_periods_3_day,ECON 024_periods_3_end,ECON 024_periods_3_start,ECON 036_location,ECON 036_periods_0_day,ECON 036_periods_0_end,ECON 036_periods_0_start,ECON 036_periods_1_day,ECON 036_periods_1_end,ECON 036_periods_1_start,ECON 036_periods_2_day,ECON 036_periods_2_end,ECON 036_periods_2_start,ECON 036_periods_3_day,ECON 036_periods_3_end,ECON 036_periods_3_start,ENGL 028_location,ENGL 028_periods_0_day,ENGL 028_periods_0_end,ENGL 028_periods_0_start,ENGL 028_periods_1_day,ENGL 028_periods_1_end,ENGL 028_periods_1_start,ENGL 028_periods_2_day,ENGL 028_periods_2_end,ENGL 028_periods_2_start,ENGL 028_periods_3_day,ENGL 028_periods_3_end,ENGL 028_periods_3_start,ENGL 047_location,ENGL 047_periods_0_day,ENGL 047_periods_0_end,ENGL 047_periods_0_start,ENGL 047_periods_1_day,ENGL 047_periods_1_end,ENGL 047_periods_1_start,ENGL 047_periods_2_day,ENGL 047_periods_2_end,ENGL 047_periods_2_start,ENGL 047_periods_3_day,ENGL 047_periods_3_end,ENGL 047_periods_3_start,ENGL 067_location,ENGL 067_periods_0_day,ENGL 067_periods_0_end,ENGL 067_periods_0_start,ENGL 067_periods_1_day,ENGL 067_periods_1_end,ENGL 067_periods_1_start,ENGL 067_periods_2_day,ENGL 067_periods_2_end,ENGL 067_periods_2_start,ENGS 022_location,ENGS 022_periods_0_day,ENGS 022_periods_0_end,ENGS 022_periods_0_start,ENGS 022_periods_1_day,ENGS 022_periods_1_end,ENGS 022_periods_1_start,ENGS 022_periods_2_day,ENGS 022_periods_2_end,ENGS 022_periods_2_start,ENGS 022_periods_3_day,ENGS 022_periods_3_end,ENGS 022_periods_3_start,ENGS 025_location,ENGS 025_periods_0_day,ENGS 025_periods_0_end,ENGS 025_periods_0_start,ENGS 025_periods_1_day,ENGS 025_periods_1_end,ENGS 025_periods_1_start,ENGS 025_periods_2_day,ENGS 025_periods_2_end,ENGS 025_periods_2_start,ENGS 025_periods_3_day,ENGS 025_periods_3_end,ENGS 025_periods_3_start,ENGS 069_location,ENGS 069_periods_0_day,ENGS 069_periods_0_end,ENGS 069_periods_0_start,ENGS 069_periods_1_day,ENGS 069_periods_1_end,ENGS 069_periods_1_start,ENGS 069_periods_2_day,ENGS 069_periods_2_end,ENGS 069_periods_2_start,ENGS 069_periods_3_day,ENGS 069_periods_3_end,ENGS 069_periods_3_start,ENGS 093_location,ENGS 093_periods_0_day,ENGS 093_periods_0_end,ENGS 093_periods_0_start,ENGS 093_periods_1_day,ENGS 093_periods_1_end,ENGS 093_periods_1_start,ENGS 093_periods_2_day,ENGS 093_periods_2_end,ENGS 093_periods_2_start,ENGS 093_periods_3_day,ENGS 093_periods_3_end,ENGS 093_periods_3_start,FILM 051_location,FILM 051_periods_0_day,FILM 051_periods_0_end,FILM 051_periods_0_start,FILM 051_periods_1_day,FILM 051_periods_1_end,FILM 051_periods_1_start,FILM 051_periods_2_day,FILM 051_periods_2_end,FILM 051_periods_2_start,GERM 001_location,GERM 001_periods_0_day,GERM 001_periods_0_end,GERM 001_periods_0_start,GERM 001_periods_1_day,GERM 001_periods_1_end,GERM 001_periods_1_start,GERM 001_periods_2_day,GERM 001_periods_2_end,GERM 001_periods_2_start,GERM 001_periods_3_day,GERM 001_periods_3_end,GERM 001_periods_3_start,GERM 001_periods_4_day,GERM 001_periods_4_end,GERM 001_periods_4_start,HIST 051_location,HIST 051_periods_0_day,HIST 051_periods_0_end,HIST 051_periods_0_start,HIST 051_periods_1_day,HIST 051_periods_1_end,HIST 051_periods_1_start,HIST 051_periods_2_day,HIST 051_periods_2_end,HIST 051_periods_2_start,HIST 051_periods_3_day,HIST 051_periods_3_end,HIST 051_periods_3_start,JAPN 033_location,JAPN 033_periods_0_day,JAPN 033_periods_0_end,JAPN 033_periods_0_start,JAPN 033_periods_1_day,JAPN 033_periods_1_end,JAPN 033_periods_1_start,JAPN 033_periods_2_day,JAPN 033_periods_2_end,JAPN 033_periods_2_start,JAPN 033_periods_3_day,JAPN 033_periods_3_end,JAPN 033_periods_3_start,LAT 003_location,LAT 003_periods_0_day,LAT 003_periods_0_end,LAT 003_periods_0_start,LAT 003_periods_1_day,LAT 003_periods_1_end,LAT 003_periods_1_start,LAT 003_periods_2_day,LAT 003_periods_2_end,LAT 003_periods_2_start,LAT 003_periods_3_day,LAT 003_periods_3_end,LAT 003_periods_3_start,M&SS 045_location,M&SS 045_periods_0_day,M&SS 045_periods_0_end,M&SS 045_periods_0_start,M&SS 045_periods_1_day,M&SS 045_periods_1_end,M&SS 045_periods_1_start,M&SS 045_periods_2_day,M&SS 045_periods_2_end,M&SS 045_periods_2_start,M&SS 045_periods_3_day,M&SS 045_periods_3_end,M&SS 045_periods_3_start,MATH 013_location,MATH 013_periods_0_day,MATH 013_periods_0_end,MATH 013_periods_0_start,MATH 013_periods_1_day,MATH 013_periods_1_end,MATH 013_periods_1_start,MATH 013_periods_2_day,MATH 013_periods_2_end,MATH 013_periods_2_start,MATH 013_periods_3_day,MATH 013_periods_3_end,MATH 013_periods_3_start,MATH 022_location,MATH 022_periods_0_day,MATH 022_periods_0_end,MATH 022_periods_0_start,MATH 022_periods_1_day,MATH 022_periods_1_end,MATH 022_periods_1_start,MATH 022_periods_2_day,MATH 022_periods_2_end,MATH 022_periods_2_start,MATH 022_periods_3_day,MATH 022_periods_3_end,MATH 022_periods_3_start,MATH 023_location,MATH 023_periods_0_day,MATH 023_periods_0_end,MATH 023_periods_0_start,MATH 023_periods_1_day,MATH 023_periods_1_end,MATH 023_periods_1_start,MATH 023_periods_2_day,MATH 023_periods_2_end,MATH 023_periods_2_start,MATH 023_periods_3_day,MATH 023_periods_3_end,MATH 023_periods_3_start,MUS 003_location,MUS 003_periods_0_day,MUS 003_periods_0_end,MUS 003_periods_0_start,MUS 003_periods_1_day,MUS 003_periods_1_end,MUS 003_periods_1_start,MUS 003_periods_2_day,MUS 003_periods_2_end,MUS 003_periods_2_start,MUS 016_location,MUS 016_periods_0_day,MUS 016_periods_0_end,MUS 016_periods_0_start,MUS 016_periods_1_day,MUS 016_periods_1_end,MUS 016_periods_1_start,MUS 016_periods_2_day,MUS 016_periods_2_end,MUS 016_periods_2_start,NAS 008_location,NAS 008_periods_0_day,NAS 008_periods_0_end,NAS 008_periods_0_start,NAS 008_periods_1_day,NAS 008_periods_1_end,NAS 008_periods_1_start,NAS 008_periods_2_day,NAS 008_periods_2_end,NAS 008_periods_2_start,NAS 008_periods_3_day,NAS 008_periods_3_end,NAS 008_periods_3_start,NAS 035_location,NAS 035_periods_0_day,NAS 035_periods_0_end,NAS 035_periods_0_start,NAS 035_periods_1_day,NAS 035_periods_1_end,NAS 035_periods_1_start,NAS 035_periods_2_day,NAS 035_periods_2_end,NAS 035_periods_2_start,NAS 035_periods_3_day,NAS 035_periods_3_end,NAS 035_periods_3_start,PSYC 028_location,PSYC 028_periods_0_day,PSYC 028_periods_0_end,PSYC 028_periods_0_start,PSYC 028_periods_1_day,PSYC 028_periods_1_end,PSYC 028_periods_1_start,PSYC 028_periods_2_day,PSYC 028_periods_2_end,PSYC 028_periods_2_start,PSYC 028_periods_3_day,PSYC 028_periods_3_end,PSYC 028_periods_3_start,REL 018_location,REL 018_periods_0_day,REL 018_periods_0_end,REL 018_periods_0_start,REL 018_periods_1_day,REL 018_periods_1_end,REL 018_periods_1_start,REL 018_periods_2_day,REL 018_periods_2_end,REL 018_periods_2_start,REL 018_periods_3_day,REL 018_periods_3_end,REL 018_periods_3_start,SPAN 003_location,SPAN 003_periods_0_day,SPAN 003_periods_0_end,SPAN 003_periods_0_start,SPAN 003_periods_1_day,SPAN 003_periods_1_end,SPAN 003_periods_1_start,SPAN 003_periods_2_day,SPAN 003_periods_2_end,SPAN 003_periods_2_start,SPAN 003_periods_3_day,SPAN 003_periods_3_end,SPAN 003_periods_3_start,SPAN 003_periods_4_day,SPAN 003_periods_4_end,SPAN 003_periods_4_start,TUCK 003_location,TUCK 003_periods_0_day,TUCK 003_periods_0_end,TUCK 003_periods_0_start,TUCK 003_periods_1_day,TUCK 003_periods_1_end,TUCK 003_periods_1_start,TUCK 003_periods_2_day,TUCK 003_periods_2_end,TUCK 003_periods_2_start
0,silsby-rocky,1,12:20,11:15,3,12:20,11:15,5,12:20,11:15,2,12:50,12:00,lsb,2,11:50,10:00,4,11:50,10:00,3,15:50,15:00,lsb,2,11:50,10:00,4,11:50,10:00,3,15:50,15:00,reed,1,09:50,09:00,2,09:50,09:00,4,09:50,09:00,5,09:50,09:00,3,09:50,09:00,kemeny,2,17:50,16:00,4,17:50,16:00,1,17:50,17:00,baker-berry,1,14:50,13:45,3,14:50,13:45,5,14:50,13:45,4,13:50,13:00,moore,2,15:50,14:00,4,15:50,14:00,3,17:05,16:15,sudikoff,1,16:50,15:00,1,17:50,17:00,4,17:50,16:00,kemeny,1,13:35,12:30,3,13:35,12:30,5,13:35,12:30,2,13:50,13:00,sudikoff,1,14:50,13:45,3,14:50,13:45,5,14:50,13:45,4,13:50,13:00,lsb,1,14:50,13:45,3,14:50,13:45,5,14:50,13:45,4,13:50,13:00,lsb,1,11:05,10:00,3,11:05,10:00,5,11:05,10:00,4,12:50,12:00,sudikoff,2,17:50,16:00,4,17:50,16:00,1,17:50,17:00,sudikoff,2,15:50,14:00,4,15:50,14:00,3,17:05,16:15,steele,2,15:50,14:00,4,15:50,14:00,3,17:05,16:15,sudikoff,1,12:20,11:15,3,12:20,11:15,5,12:20,11:15,2,12:50,12:00,sudikoff,2,15:50,14:00,4,15:50,14:00,3,17:05,16:15,sudikoff,2,11:50,10:00,4,11:50,10:00,3,15:50,15:00,lsb,1,12:20,11:15,3,12:20,11:15,5,12:20,11:15,2,12:50,12:00,silsby-rocky,1,09:50,08:45,3,09:50,08:45,5,09:50,08:45,4,09:50,09:00,kemeny,1,09:50,08:45,3,09:50,08:45,5,09:50,08:45,4,09:50,09:00,lsb,1,09:50,08:45,3,09:50,08:45,5,09:50,08:45,4,09:50,09:00,dartmouth_hall,1,12:20,11:15,3,12:20,11:15,5,12:20,11:15,2,12:50,12:00,carson-tech_services,2,15:50,14:00,4,15:50,14:00,3,17:05,16:15,cummings,1,09:50,08:45,3,09:50,08:45,5,09:50,08:45,4,09:50,09:00,cummings,1,14:50,13:45,3,14:50,13:45,5,14:50,13:45,4,13:50,13:00,lsb,1,11:05,10:00,3,11:05,10:00,5,11:05,10:00,4,12:50,12:00,maclean,1,13:35,12:30,3,13:35,12:30,5,13:35,12:30,2,13:50,13:00,vac,2,11:50,10:00,4,11:50,10:00,3,15:50,15:00,dartmouth_hall,1,09:50,09:00,2,09:50,09:00,4,09:50,09:00,5,09:50,09:00,3,09:50,09:00,carson-tech_services,1,13:35,12:30,3,13:35,12:30,5,13:35,12:30,2,13:50,13:00,batrlett,1,12:20,11:15,3,12:20,11:15,5,12:20,11:15,2,12:50,12:00,reed,1,09:50,08:45,3,09:50,08:45,5,09:50,08:45,4,09:50,09:00,kemeny,1,09:50,08:45,3,09:50,08:45,5,09:50,08:45,4,09:50,09:00,kemeny,1,13:35,12:30,3,13:35,12:30,5,13:35,12:30,2,13:50,13:00,kemeny,1,12:20,11:15,3,12:20,11:15,5,12:20,11:15,2,12:50,12:00,kemeny,1,12:20,11:15,3,12:20,11:15,5,12:20,11:15,2,12:50,12:00,hopkins,2,15:50,14:00,4,15:50,14:00,3,17:05,16:15,hopkins,2,11:50,10:00,4,11:50,10:00,3,15:50,15:00,moore,1,13:35,12:30,3,13:35,12:30,5,13:35,12:30,2,13:50,13:00,carpenterhall,1,12:20,11:15,3,12:20,11:15,5,12:20,11:15,2,12:50,12:00,moore,1,14:50,13:45,3,14:50,13:45,5,14:50,13:45,4,13:50,13:00,carson-tech_services,1,14:50,13:45,3,14:50,13:45,5,14:50,13:45,4,13:50,13:00,dartmouth_hall,1,09:50,09:00,2,09:50,09:00,4,09:50,09:00,5,09:50,09:00,3,09:50,09:00,carson-tech_services,2,15:50,14:00,4,15:50,14:00,3,17:05,16:15

To open 'class.csv', add header to 'class.csv' for each column.

Add this:
User,Class1,Class2,Class3,Class4

In [29]:
cls = pd.read_csv('../../../student-life-dataset/dataset/education/class.csv')

In [31]:
cls.head()

  User    Class1    Class2    Class3 Class4
0  u00       NaN       NaN       NaN    NaN
1  u01  ENGS 069  ENGS 022  ANTH 012    NaN
2  u02  COSC 077  COSC 098  COSC 065    NaN
3  u03  COSC 057  COSC 065       NaN    NaN
4  u04  COSC 065       NaN       NaN    NaN

# Deadlines

deadline.csv records the number of class deadlines for each participant from March 27, 2013 to June 5, 2013. Class deadlines include homework deadlines, projects, quiz, mid-terms and finals.

In [32]:
deadlines = pd.read_csv('../../../student-life-dataset/dataset/education/deadlines.csv')

In [38]:
deadlines = deadlines.dropna(how='all', axis=1)

In [39]:
show_full_data(deadlines.sample(5))

,uid,2013-03-27,2013-03-28,2013-03-29,2013-03-30,2013-03-31,2013-04-01,2013-04-02,2013-04-03,2013-04-04,2013-04-05,2013-04-06,2013-04-07,2013-04-08,2013-04-09,2013-04-10,2013-04-11,2013-04-12,2013-04-13,2013-04-14,2013-04-15,2013-04-16,2013-04-17,2013-04-18,2013-04-19,2013-04-20,2013-04-21,2013-04-22,2013-04-23,2013-04-24,2013-04-25,2013-04-26,2013-04-27,2013-04-28,2013-04-29,2013-04-30,2013-05-01,2013-05-02,2013-05-03,2013-05-04,2013-05-05,2013-05-06,2013-05-07,2013-05-08,2013-05-09,2013-05-10,2013-05-11,2013-05-12,2013-05-13,2013-05-14,2013-05-15,2013-05-16,2013-05-17,2013-05-18,2013-05-19,2013-05-20,2013-05-21,2013-05-22,2013-05-23,2013-05-24,2013-05-25,2013-05-26,2013-05-27,2013-05-28,2013-05-29,2013-05-30,2013-05-31,2013-06-01,2013-06-02,2013-06-03,2013-06-04,2013-06-05
35,u49,2,1,2,0,0,2,1,2,1,2,0,0,3,1,2,1,2,0,0,3,1,2,2,2,0,0,3,1,2,1,2,0,0,2,2,2,1,2,0,0,2,2,2,2,2,0,0,3,1,2,1,2,0,0,2,1,2,1,2,0,0,2,1,2,0,1,0,0,1,0,0
1,u02,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,2,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
8,u10,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,2,0,0,0,0,0,0,2,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,0,0,1,0,0,0,0
28,u35,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0
36,u50,0,0,0,0,0,1,0,0,0,0,0,0,2,0,0,0,0,0,0,2,0,0,0,0,0,0,2,0,0,0,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0

# Grades

In [40]:
grades = pd.read_csv('../../../student-life-dataset/dataset/education/grades.csv')

In [41]:
grades.head()

   uid   gpa all   gpa 13s   cs 65
0  u01     2.863  1.777778     3.0
1  u02     3.505  4.000000     4.0
2  u04     3.029  3.500000     4.0
3  u05     3.679  3.777778     4.0
4  u07     3.474  4.000000     4.0

# Piazza Usage

In [42]:
piazza = pd.read_csv('../../../student-life-dataset/dataset/education/piazza.csv')

In [43]:
piazza.head()

   uid  days online  views  contributions  questions  notes  answers
0  u00           49    162            144          0     67       22
1  u01           29    299              5          1      1        0
2  u02           57    299              0          0      0        0
3  u03           47    262             30         15      2        6
4  u04           27    101              1          1      0        0